title: "MK-ch@0t!c_Syst&m"
author: "Gianmario `MonKeed` Merisio"
description: "Copyright ©2024 Gianmario Merisio.
  Unless otherwise noted, all blog posts, photos, graphics, presentations, and other media are licensed under <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1'>CC BY-NC-SA 4.0</a>.
  Unless otherwise noted, all code snippets are available under the <a href='https://unlicense.org/'>Unlicense</a>.
  Powered by <a href='https://jekyllrb.com/'>Jekyll</a> with <a href='https://jekyllthemes.io/theme/contrast'>Constrast</a> theme.
  Hosted by <a href='https://pages.github.com/'>GitHub Pages</a>. 
  Reach me out on my socials or via e-mail down below."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true  # show article excerpts on the home page
show_frame: true  # adds a gray frame to the site
show_sidebar: false  # show a sidebar instead of the usual header

# Menu
navigation:  # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "archive.html"}
  # - {file: "about.md"}

external:  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:gianmariomerisio@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/MonKeed"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/gianmario-merisio/"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/monkeed_5e/"}
  - {title: X, icon: square-x-twitter, url: "https://twitter.com/MonKeed"}
  - {title: OrcID, icon: orcid, url: "https://orcid.org/0000-0001-8806-7952"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Gianmario-Merisio"}
  - {title: GoogleScholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=nrEKPxYAAAAJ&hl=en"}

comments:
#  disqus_shortname: ""  # see https://disqus.com/
#  isso_domain: ""  # see https://posativ.org/isso/

# plugins:
#  - jekyll-feed
